### ISSUE TITLE
add option to set initial permissions for files or folders

### ISSUE THREAD

**Issue by boschkundendienst** [pheditor/pheditor#27]
Hi, thanks for this wonderful small editor which works great.

I have an account at freeshell.de where newly created folders get permission `0700` and newly created files get `0600`. I had to change your script a little bit to set this permissions automatically with pheditor.php to `0755` for directories and `0644` for files to make the accessible via the website.

Since I am not a PHP coder I will send you my tweaks here which you could maybe incorporate in a future release?

```php
// all the other Pheditor constants before
define('MKDIR', 0755);
define('MKFILE', 0644);
```

now at every file or directory operation I added something like this using either `MKDIR` or `MKFILE` constant for the permissions

```php
...
// within 'make-dir'
if (file_exists($dir) === false) {
                //mkdir($dir);
                mkdir($dir, MKDIR); //with permissions but could still fail when server setup is strange
                chmod($dir, MKDIR);  // do it again MKDIR must be octal
...

For a final versions a check should be implemented if the `MKDIR` and `MKFILE` constants where set and only then change and so on...

Thanks for this nice tool!

Regards

Bosch

**Comment by hamidsamak** [comment]
Hi,
Thanks for your suggestion. Done https://github.com/pheditor/pheditor/commit/3bfac537a1f3b2ecf4d7d63f33537efcb81c4e8e
