### ISSUE TITLE
Display directory before files

### ISSUE THREAD

**Issue by ITSBed** [pheditor/pheditor#32]
Nice little editor!
I prefer too to have directory before files.
I hope the existing pull request could be included.
#https://github.com/pheditor/pheditor/pull/22

**Comment by gaffling** [comment]
implemented it and it works very nice, thanks a lot

**Comment by hamidsamak** [comment]
This feature implemented in commit below with changing JStree files reload to remote mode:
https://github.com/pheditor/pheditor/commit/4fdcd0567263aa1415414b33994b7e7f013dd1c1
