### ISSUE TITLE
Edit files one directory up

### ISSUE THREAD

**Issue by ITSBed** [pheditor/pheditor#33]
Nice little editor!
I put pheditor in a subdirectory and edit files one directory up:
`define('MAIN_DIR', dirname(__DIR__, 1));	// One (1) level up`

To keep the log and history in the same place as pheditor I modify these:
```
define('LOG_FILE', __DIR__ . DS . '.phedlog');
define('HISTORY_PATH', __DIR__ . DS . '.phedhistory');
```
Under this usage (one directory up) I want to add a feature to hide the pheditor's self directory:
`define('SHOW_PHP_SELF_DIR', false);`
```
	foreach ($files as $key => $file) {
		if ((SHOW_PHP_SELF === false && $dir . DS . $file == __FILE__) || (SHOW_HIDDEN_FILES === false && substr($file, 0, 1) === '.') || (SHOW_PHP_SELF_DIR === false && $dir . DS . $file == __DIR__)) {
```
Sorry I don't know how to suggest to include this to your code

**Comment by gaffling** [comment]
implemented it and it works very nice, thanks a lot
