### ISSUE TITLE
Javascript sha512 and Chrome on http

### ISSUE THREAD

**Issue by zajako** [pheditor/pheditor#36]
So there an issue with using this editor on a http based website due to chrome blocking the use of encryption based features unless you are using https.

The result is, no files are able to load for editing.

Screenshot of the error in console:  https://share.zajako.com/nOunvz2o

Simple text error:  phpeditor.php:210 Uncaught TypeError: Cannot read property 'digest' of undefined at sha512 (phpeditor.php:210)

This can be duplicated by uploading the file on a site using http and then opening it in chrome.

Possible solutions are to use an alternative crypto method like this: https://github.com/emn178/js-sha256

**Comment by gaffling** [comment]
for me it works on localhost and chrome without SSL, or do you have these problems only on a real domain?

**Comment by zajako** [comment]
Maybe chrome enables the functions for local host assuming that https  is unlikely. Yes I was using it with a real domain on a prototype site to enable a friend to try to edit a few files.

**Comment by gaffling** [comment]
Thanks for your replay, will check that with the script online and will give feedback here ;-)

**Comment by hamidsamak** [comment]
As it is replied in [this topic](https://stackoverflow.com/questions/46670556/how-to-enable-crypto-subtle-for-unsecure-origins-in-chrome) crypto.subtle is disabled in Chrome for non-SSL websites. But there is no problem for `localhost`.

**Comment by hamidsamak** [comment]
Built-in web browser SHA512 function replaced with js-sha512 package for better functionality in all browsers:
https://github.com/pheditor/pheditor/commit/e4308f5e48796540d43f5708dd439fd5b7aabd78
