### ISSUE TITLE
running pheditor in docker

### ISSUE THREAD

**Issue by farvardin** [pheditor/pheditor#37]
hello,

I'm trying to run pheditor in docker (using php:apache)

I can login, see the files names. But when I click on a file, it only displays empty content. There are all the necessary rights on the file so I should be able to edit them. It works on a normal server installation.

Do you have any idea?

![image](https://user-images.githubusercontent.com/477243/96865223-f6d1d380-1469-11eb-9afb-e648da6cbfbd.png)

**Comment by gaffling** [comment]
for me it doesn't work if I have a space-char in a dir name, maybe you can check this too?!

**Comment by RaHahda** [comment]
Maybe this is the same problem I encountered with bookmarks...
Please check [issue #40 ](https://github.com/pheditor/pheditor/issues/40) and the workaround.

Best regards
Ralf

**Comment by DeBaschdi** [comment]
Same Problem here :/  issue #40 did not reslove this error

**Comment by hamidsamak** [comment]
Hi,
Please make sure that you are browsing Pheditor in SSL mode. 
https://github.com/pheditor/pheditor/issues/36

Anyway, I have replaced the built-in browser SHA512 with the js-sha512 library. Now it is working on 80 port as well.
https://github.com/pheditor/pheditor/commit/e4308f5e48796540d43f5708dd439fd5b7aabd78

**Comment by DeBaschdi** [comment]
> Hi,
> Please make sure that you are browsing Pheditor in SSL mode.
> #36
> 
> Anyway, I have replaced the built-in browser SHA512 with the js-sha512 library. Now it is working on 80 port as well.
> [e4308f5](https://github.com/pheditor/pheditor/commit/e4308f5e48796540d43f5708dd439fd5b7aabd78)

Thx , this slove my Problem :)
