### ISSUE TITLE
Required js and css files

### ISSUE THREAD

**Issue by marco-trovato** [pheditor/pheditor#45]
"Single-file editor" until it needs several other js and css files in order to work.

My old version stopped working because the old CDN is not available anymore, in that moment I realized this is not a "single-file" utility.

Is it possible to have an assets folder containing all the necessary files?

Thank you! ❤️ your software is awesome!

**Comment by hamidsamak** [comment]
Yes, we can have required static files as separate packages and install them using a package manager like npm.
I will put it on the project task list.

Thank's for your suggestion.

**Comment by marco-trovato** [comment]
Any news on this?
I'm having trouble because i uploaded it on my webserver and it now **stopped working** 😭

**Comment by hamidsamak** [comment]
Hi @marco-trovato,

Please clone the latest version of project and read Local assets section in readme file from link below.

[Local assets guide](https://github.com/pheditor/pheditor#local-assets)
