### ISSUE TITLE
Editor doesnt works

### ISSUE THREAD

**Issue by denq04** [pheditor/pheditor#55]
Files/folders structure showing correctly, but not showing any file content. With local assets the same.
Terminal works only for one command usage, then need to reload page or it saying "Command not found" for the same command. What i am missing?

**Comment by hamidsamak** [comment]
Hi @denq04 
Please check the browser console for any errors. Maybe some scripts not loaded correctly.

**Comment by denq04** [comment]
No errors in console. Only old version from releases works, latest version from main branch doesnt works

**Comment by hamidsamak** [comment]
Can you please tell about your OS name and version?

Make sure that you are cloning the latest version of repository (`main` branch).
Also check the network tab in browser console to check all scripts are loading correctly. Maybe some scripts are blocking by antivirus or network.

Besides that you can switch local assets (assets from CDN or installed by npm). Switch is in pheditor.php (Line: 29)

**Comment by denq04** [comment]
I am sorry, i dont need it now and cant check, just saying as it was. I tried to set it up on Windows Server 2019 with open server. All worked excluding editor. Files just didnt open, without any error. I tried to do it with npm and with CDN, checked file access and rights, it was the same, i cant test it now, sorry for bothering.
