### ISSUE TITLE
Typo in homepage title

### ISSUE THREAD

**Issue by CarstenGrohmann** [pheditor/pheditor#59]
Hi,

the title of your homepage at [pheditor](https://pheditor.ir/) contains a typo:

```
<title>Pheditor - PHP file edidtor</title>
```

instead of

```
<title>Pheditor - PHP file editor</title>
```

Regards,
Carsten

**Comment by hamidsamak** [comment]
Hi @CarstenGrohmann,

Thanks for the report.
