### ISSUE TITLE
List minimum requirements

### ISSUE THREAD

**Issue by CarstenGrohmann** [pheditor/pheditor#60]
Hello,

please specify the minimum required PHP version in the README.md file of the project. 

My provider threw a 500 - Internal Server Error until I switched to PHP 7.4. Specifying the minimum required PHP version would make troubleshooting easier for other users.

With kind regards,
Carsten

**Comment by hamidsamak** [comment]
Hi @CarstenGrohmann 
Sorry for delayed reply, I added requirements to readme file.
https://github.com/pheditor/pheditor/commit/bc5756fd77ab18a56c2e823c5889d09ba5987f5c

Please check PHP supported versions in the link bellow. PHP 5 is not support anymore.
https://www.php.net/supported-versions.php

Thanks
Hamid
