### ISSUE TITLE
Windows server error

### ISSUE THREAD

**Issue by lsn** [pheditor/pheditor#62]
hello,

On a windows server, the files are not loaded for editing.

**Comment by hamidsamak** [comment]
Hello @lsn,
Can you please give me more details about these:
1. Web server
2. PHP version

**Comment by lsn** [comment]
Hello,

- Apache/2.4.51 (Win64) 
- PHP Version 8.0.12

on linux server with the same Apache and Php it is working fine

**Comment by tomeky** [comment]
same issue on:

windows server 2019 / xampp (xampp-windows-x64-8.0.19-0-VS16-installer)
apache - 2.4.53
php - 8.0.19

possible to fix ti?

**Comment by hamidsamak** [comment]
Problem fixed.
https://github.com/pheditor/pheditor/commit/b6392e0503f612bcb29c2afba44b6a47eeb8098d
