### ISSUE TITLE
how to put terminal command with " "

### ISSUE THREAD

**Issue by ringneck** [pheditor/pheditor#70]
Hi,

it does not work some terminal command woth "", ''

such as 

asterisk -rx 'dialplan reload'

asterisk -rx "dialplan reload"

it seems to more like asterisk -rx "dialplan reload"

letmeknow some hint

thanks

**Comment by hamidsamak** [comment]
Hi @ringneck 
Working with quote and double quote seems ok. I've tested it with ```grep -Ril 'aaa' .``` and ```grep -Ril "aaa" .``` commands.
You can change ```aaa``` to any other string that is not contains in source code, then the result will be empty.

Can you give me more details about OS, PHP version, webserver and any other settings or configs in your ```pheditor.php``` file?
