### ISSUE TITLE
CDN packages update

### ISSUE THREAD

**Issue by slolo2000** [pheditor/pheditor#71]
Hello,

Do you think you could make a new version oh pheditor with CDN packages update.

For example:
JQuery from v3.3.1 to v3.7.0
Twitter bootstrap from v4.3.1 to v4.6.2
fontawesome from 5.15.1 to 5.15.4 (or the last v6.4.2)
CodeMirror from v5.43.0 to the last v5.56.14 version (v6 exists but not sure if there is broken changes)
JsHint from v2.10.2 to v2.13.6
JsTree from v3.3.7 to v3.3.15
...

Thanks for your work on this great project.

**Comment by hamidsamak** [comment]
Hi @slolo2000,

CDN libraries and packages updated to latest version hosted on cdnjs.
https://github.com/pheditor/pheditor/commit/58362cf85f45de600d6c7aa9ecdd1b32eee7dbb5
