### ISSUE TITLE
Directories with a plus (+) in the name can't be opened

### ISSUE THREAD

**Issue by reeno** [pheditor/pheditor#77]
Hello,

I created the following directory structure:

```
./index.html
./dir/index.html
./dir+/index.html
./dir+dir/index.html
```

In Pheditor, I see all the directories:
![grafik](https://github.com/pheditor/pheditor/assets/417984/7cf11d74-ae09-4e68-9c19-16dba9cdcd0e)
I can also open `dir`
![grafik](https://github.com/pheditor/pheditor/assets/417984/d3019756-6738-48fc-a627-38ac6e03f90a)
But clicking on the arrow before `dir+` just removes the arrow and nothing happens:
![grafik](https://github.com/pheditor/pheditor/assets/417984/6296b2f4-1083-4421-82e2-49ae7854c994)
Request is successful:
![grafik](https://github.com/pheditor/pheditor/assets/417984/f8e6164b-004b-470f-8c0a-8d5783b63a7a)
but returns an empty JSON
![grafik](https://github.com/pheditor/pheditor/assets/417984/768b6331-8d4b-4fdb-aa33-437f3d9bf0fb)
Same for `dir+dir`
![grafik](https://github.com/pheditor/pheditor/assets/417984/1d89949b-a4a6-4f30-a3d7-75b4b0f586f2)

The `+` probably needs to be escaped.

**Comment by hamidsamak** [comment]
Hi @reeno 

Sorry for the delay in responding. The issue has been resolved now. Thank you for your patience.
