### ISSUE TITLE
doesn't launch

### ISSUE THREAD

**Issue by heng1a** [pheditor/pheditor#78]
I get this error:
 Parse error: syntax error, unexpected '[' in C:\server2go\htdocs\wrum\pheditor-2.0.1\pheditor.php on line 31

**Comment by lematangtv** [comment]
same problem. solution please?

**Comment by hamidsamak** [comment]
Hi,
Please give me information about your OS, PHP version and web-server. I guess your PHP version is 5. Please look at the requirements [here](https://github.com/pheditor/pheditor#requirements).
