### ISSUE TITLE
Folders with spaces not working

### ISSUE THREAD

**Issue by trickjarrett** [pheditor/pheditor#79]
I just downloaded and gave this a try, as I was browsing a structure that I have backed up onto my server (thus why the folders sometimes have spaces) I discovered that I cannot expand and collapse the folders when there are any spaces in the folder names.

**Comment by hamidsamak** [comment]
Hi @trickjarrett 

Latest mainline version seems ok. Please use latest `pheditor.php` from main branch:
https://raw.githubusercontent.com/pheditor/pheditor/refs/heads/main/pheditor.php

Please give me more details about your OS, php version if was not ok.
